export async function GET() {
    const flowers = [
        {
            id: 1,
            name: "Daisy",
            price: 50,
            salePrice: 0,
            description: "Small, low-growing plant with signature white petals and a yellow center. Blooms from spring to late summer.",
            isSale: false,
            saleDiscount: 0,
            type: "none",
            category: "Big Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509675/epvsf1qssg76utozbafn.jpg"
        },
        {
            id: 2,
            name: "Pansy",
            price: 60,
            salePrice: 0,
            description: "Small, colorful flower with velvety petals in Trerrariumss of purple, blue, yellow, and white. Blooms during cool weather seasons.",
            isSale: true,
            saleDiscount: 13,
            type: "new",
            category: "House Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509997/zyozcmd3dwbhfgxd9vly.jpg"
        },
        {
            id: 3,
            name: "Marigold",
            price: 75,
            salePrice: 0,
            description: "Small, bushy plant with gold, orange, or yellow flowers that attract butterflies and bees. Blooms from summer to fall.",
            isSale: false,
            saleDiscount: 0,
            type: "none",
            category: "Gardening",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510339/njtbsczrcm8cs4pnuftr.jpg"
        },
        {
            id: 4,
            name: "Cactus",
            price: 90,
            salePrice: 0,
            description: "Drought-resistant plant with thick, spiny stems and minimal leaves. Perfect for dry climates.",
            isSale: true,
            saleDiscount: 20,
            type: "exotic",
            category: "Succulents",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510624/dxsq041t63mkhl8mm2pr.jpg"
        },
        {
            id: 5,
            name: "Lavender",
            price: 85,
            salePrice: 0,
            description: "Fragrant purple flowers known for their calming scent. Used in aromatherapy and herbal remedies.",
            isSale: false,
            saleDiscount: 0,
            type: "new",
            category: "Gardening",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509675/epvsf1qssg76utozbafn.jpg"
        },
        {
            id: 6,
            name: "Bamboo",
            price: 120,
            salePrice: 0,
            description: "Tall, fast-growing grass-like plant often used for decoration and construction.",
            isSale: true,
            saleDiscount: 15,
            type: "none",
            category: "Small Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509997/zyozcmd3dwbhfgxd9vly.jpg"
        },
        {
            id: 7,
            name: "Orchid",
            price: 150,
            salePrice: 0,
            description: "Elegant and delicate flowers with unique shapes and vibrant colors.",
            isSale: false,
            saleDiscount: 0,
            type: "exotic",
            category: "Gardening",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510339/njtbsczrcm8cs4pnuftr.jpg"
        },
        {
            id: 8,
            name: "Fern",
            price: 65,
            salePrice: 0,
            description: "Lush green plant with feathery leaves, perfect for humid environments.",
            isSale: true,
            saleDiscount: 10,
            type: "none",
            category: "Trerrariums",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510624/dxsq041t63mkhl8mm2pr.jpg"
        },
        {
            id: 9,
            name: "Foyu",
            price: 50,
            salePrice: 0,
            description: "Small, low-growing plant with signature white petals and a yellow center. Blooms from spring to late summer.",
            isSale: false,
            saleDiscount: 0,
            type: "none",
            category: "House Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509675/epvsf1qssg76utozbafn.jpg"
        },
        {
            id: 10,
            name: "Qimmatdee",
            price: 2000,
            salePrice: 0,
            description: "Small, colorful flower with velvety petals in Trerrariumss of purple, blue, yellow, and white. Blooms during cool weather seasons.",
            isSale: true,
            saleDiscount: 50,
            type: "new",
            category: "Potter Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509997/zyozcmd3dwbhfgxd9vly.jpg"
        },
        {
            id: 11,
            name: "Marigold",
            price: 750,
            salePrice: 0,
            description: "Small, bushy plant with gold, orange, or yellow flowers that attract butterflies and bees. Blooms from summer to fall.",
            isSale: false,
            saleDiscount: 0,
            type: "none",
            category: "Seeds",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510339/njtbsczrcm8cs4pnuftr.jpg"
        },
        {
            id: 12,
            name: "Cactus",
            price: 900,
            salePrice: 0,
            description: "Drought-resistant plant with thick, spiny stems and minimal leaves. Perfect for dry climates.",
            isSale: true,
            saleDiscount: 20,
            type: "exotic",
            category: "Small Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510624/dxsq041t63mkhl8mm2pr.jpg"
        },
        {
            id: 13,
            name: "Lavender",
            price: 85,
            salePrice: 0,
            description: "Fragrant purple flowers known for their calming scent. Used in aromatherapy and herbal remedies.",
            isSale: false,
            saleDiscount: 0,
            type: "herbal",
            category: "Gardening",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509675/epvsf1qssg76utozbafn.jpg"
        },
        {
            id: 14,
            name: "Bamboo",
            price: 120,
            salePrice: 0,
            description: "Tall, fast-growing grass-like plant often used for decoration and construction.",
            isSale: true,
            saleDiscount: 15,
            type: "none",
            category: "Small Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509997/zyozcmd3dwbhfgxd9vly.jpg"
        },
        {
            id: 15,
            name: "Orchid",
            price: 1500,
            salePrice: 0,
            description: "Elegant and delicate flowers with unique shapes and vibrant colors.",
            isSale: true,
            saleDiscount: 23,
            type: "exotic",
            category: "Gardening",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510339/njtbsczrcm8cs4pnuftr.jpg"
        },
        {
            id: 16,
            name: "Fern",
            price: 675,
            salePrice: 0,
            description: "Lush green plant with feathery leaves, perfect for humid environments.",
            isSale: true,
            saleDiscount: 10,
            type: "none",
            category: "Succulents",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510624/dxsq041t63mkhl8mm2pr.jpg"
        },
        {
            id: 17,
            name: "Daisy",
            price: 50,
            salePrice: 0,
            description: "Small, low-growing plant with signature white petals and a yellow center. Blooms from spring to late summer.",
            isSale: false,
            saleDiscount: 0,
            type: "none",
            category: "Big Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509675/epvsf1qssg76utozbafn.jpg"
        },
        {
            id: 18,
            name: "Pansy",
            price: 60,
            salePrice: 0,
            description: "Small, colorful flower with velvety petals in Trerrariumss of purple, blue, yellow, and white. Blooms during cool weather seasons.",
            isSale: true,
            saleDiscount: 13,
            type: "new",
            category: "House Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509997/zyozcmd3dwbhfgxd9vly.jpg"
        },
        {
            id: 19,
            name: "Marigold",
            price: 75,
            salePrice: 0,
            description: "Small, bushy plant with gold, orange, or yellow flowers that attract butterflies and bees. Blooms from summer to fall.",
            isSale: false,
            saleDiscount: 0,
            type: "none",
            category: "Big Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510339/njtbsczrcm8cs4pnuftr.jpg"
        },
        {
            id: 20,
            name: "Cactus",
            price: 90,
            salePrice: 0,
            description: "Drought-resistant plant with thick, spiny stems and minimal leaves. Perfect for dry climates.",
            isSale: true,
            saleDiscount: 20,
            type: "exotic",
            category: "Succulents",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510624/dxsq041t63mkhl8mm2pr.jpg"
        },
        {
            id: 21,
            name: "Lavender",
            price: 85,
            salePrice: 0,
            description: "Fragrant purple flowers known for their calming scent. Used in aromatherapy and herbal remedies.",
            isSale: false,
            saleDiscount: 0,
            type: "new",
            category: "Gardening",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509675/epvsf1qssg76utozbafn.jpg"
        },
        {
            id: 22,
            name: "Bamboo",
            price: 120,
            salePrice: 0,
            description: "Tall, fast-growing grass-like plant often used for decoration and construction.",
            isSale: true,
            saleDiscount: 15,
            type: "none",
            category: "Small Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509997/zyozcmd3dwbhfgxd9vly.jpg"
        },
        {
            id: 23,
            name: "Orchid",
            price: 1500,
            salePrice: 0,
            description: "Elegant and delicate flowers with unique shapes and vibrant colors.",
            isSale: false,
            saleDiscount: 0,
            type: "new",
            category: "Gardening",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510339/njtbsczrcm8cs4pnuftr.jpg"
        },
        {
            id: 24,
            name: "Fern",
            price: 65,
            salePrice: 0,
            description: "Lush green plant with feathery leaves, perfect for humid environments.",
            isSale: true,
            saleDiscount: 10,
            type: "none",
            category: "Succulents",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510624/dxsq041t63mkhl8mm2pr.jpg"
        },
        {
            id: 25,
            name: "Daisy",
            price: 1680,
            salePrice: 0,
            description: "Small, low-growing plant with signature white petals and a yellow center. Blooms from spring to late summer.",
            isSale: false,
            saleDiscount: 0,
            type: "none",
            category: "Big Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509675/epvsf1qssg76utozbafn.jpg"
        },
        {
            id: 26,
            name: "Pansy",
            price: 60,
            salePrice: 0,
            description: "Small, colorful flower with velvety petals in Trerrariumss of purple, blue, yellow, and white. Blooms during cool weather seasons.",
            isSale: true,
            saleDiscount: 13,
            type: "new",
            category: "House Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509997/zyozcmd3dwbhfgxd9vly.jpg"
        },
        {
            id: 27,
            name: "Marigold",
            price: 75,
            salePrice: 0,
            description: "Small, bushy plant with gold, orange, or yellow flowers that attract butterflies and bees. Blooms from summer to fall.",
            isSale: false,
            saleDiscount: 0,
            type: "none",
            category: "Gardening",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510339/njtbsczrcm8cs4pnuftr.jpg"
        },
        {
            id: 28,
            name: "Cactus",
            price: 90,
            salePrice: 0,
            description: "Drought-resistant plant with thick, spiny stems and minimal leaves. Perfect for dry climates.",
            isSale: true,
            saleDiscount: 20,
            type: "exotic",
            category: "Small Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510624/dxsq041t63mkhl8mm2pr.jpg"
        },
        {
            id: 29,
            name: "Lavender",
            price: 1330,
            salePrice: 0,
            description: "Fragrant purple flowers known for their calming scent. Used in aromatherapy and herbal remedies.",
            isSale: false,
            saleDiscount: 0,
            type: "herbal",
            category: "Gardening",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509675/epvsf1qssg76utozbafn.jpg"
        },
        {
            id: 30,
            name: "Bamboo",
            price: 120,
            salePrice: 0,
            description: "Tall, fast-growing grass-like plant often used for decoration and construction.",
            isSale: true,
            saleDiscount: 15,
            type: "none",
            category: "Small Plants",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693509997/zyozcmd3dwbhfgxd9vly.jpg"
        },
        {
            id: 31,
            name: "Orchid",
            price: 150,
            salePrice: 0,
            description: "Elegant and delicate flowers with unique shapes and vibrant colors.",
            isSale: false,
            saleDiscount: 0,
            type: "exotic",
            category: "Gardening",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510339/njtbsczrcm8cs4pnuftr.jpg"
        },
        {
            id: 32,
            name: "Fern",
            price: 65,
            salePrice: 0,
            description: "Lush green plant with feathery leaves, perfect for humid environments.",
            isSale: true,
            saleDiscount: 10,
            type: "none",
            category: "Trerrariums",
            img1: "http://res.cloudinary.com/dj28bsagl/image/upload/v1693510624/dxsq041t63mkhl8mm2pr.jpg"
        }
    ];

    return Response.json(flowers);
}
